# Default build configuration.
# Can be overriden with `-DCMAKE_BUILD_TYPE=<Debug|RelWithDebInfo|Release|...>` when calling CMake,
# or by using an environment variable `export CMAKE_BUILD_TYPE=...`.
if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Release)
endif()
message(STATUS "CMAKE_BUILD_TYPE set to [${CMAKE_BUILD_TYPE}]")

# C++ standard for all the targets in the project.
set(CMAKE_CXX_STANDARD 17)

# Generate a `compile_commands.json` file.
# This is useful to check the compilation commands that are actually generated by CMake.
# Some IDEs and tools also rely on this file for code analysis and navigation.
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# Turn all compiler warnings into errors, unless otherwise specified.
# Remark: this requires CMake >= 3.24.
set(CMAKE_COMPILE_WARNING_AS_ERROR ON)

# Enable compiler warnings.
if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")

    # Reference: https://learn.microsoft.com/en-us/cpp/build/reference/compiler-option-warning-level
    add_compile_options(
        /W4  # Recommended default setting

        # FIXME Significant legacy code refactoring would be necessary to address these warnings properly
        # (in particular, it would require to carefully review the integral types used to encode
        # the inputs and outputs of graph algorithm functions).
        /wd4244  # Type conversion with possible loss of precision
        /wd4267  # Conversion from 'size_t' to smaller integral type
    )

elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|.*Clang")

    # Reference: https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
    add_compile_options(
        -Wall       # Recommended default setting
        -Wextra     # Additional warnings, also recommended by default
        -Wpedantic  # Enforce strict ISO C++ compliance
    )

endif()
