name: CI

jobs:
  test:
    runs-on:${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.9"]
        
    steps:
      - name: Checkout source
        uses: actions/checkout@develop
